<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<!-- BEGIN (write your solution here) -->
<?php if (!isset($authenticatedUser)): ?>
    <form action="/session" method="post">
        <div>
            <label>
                Name
                <input type="text" name="user[name]"
            </label>
            <label>
                Password
                <input type="text" name="user[password]"
            </label>
            <div>
                <input type="submit" value="Sign In">
    </form>
<?php else: ?>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <div>
            <?= $authenticatedUser['name'] ?>
        </div>
        <input type="submit" value="Sign Out">
    </form>
<?php endif;?>
<!-- END -->

