<form action="/users" method="post">
    <h1>New User</h1>
    <hr>
    <div>
        <label>
            ID:
            <input type="text" required name="user[id]" value="<?= htmlspecialchars($user['id'])?>">
        </label>
        <label>
            Nickname:
            <input type="text" required name="user[nickname]" value="<?= htmlspecialchars($user['nickname'])?>">
        </label>
        <br>
        <?php if (isset($errors['nickname'])): ?>
            <div>
                <?= $errors['nickname'] ?>
            </div>
        <?php endif ?>
        <label>
            Email:
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['nickname'])?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div>
                <?= $errors['email'] ?>
            </div>
        <?php endif ?>
    </div>
    <input type="submit" value="Create">
</form>